
services:

  postgres:
    image: postgres:15
    container_name: lending-postgres
    restart: always
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst123
      POSTGRES_DB: lendingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: lending-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: lending-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  metabase:
    image: metabase/metabase
    container_name: lending-metabase
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  mysql_data:
  mongo_data: